### ISSUE TITLE
understanding class_tokens

### ISSUE THREAD

**Issue by ledahu** [derrian-distro/LoRA_Easy_Training_Scripts#189]
Hi, i don't know if its an issue :/ 

i have folders in my dataset : 

- 1_classname : reg image without caption file

- XX_TRIGGER classname : my training image with caption files

When i start training i get a warnin for each reg image "_neither caption file nor class tokens are found. use empty caption for PATH_TO_IMG_"

and then in the training start log : 

```
  [Subset 3 of Dataset 0]
    image_dir: "X_TRIGGER classname"
    image_count: 123
    num_repeats: X
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: None
    caption_extension: .txt
```

and reg 

```
  [Subset 1 of Dataset 0]
    image_dir: "1_classname"
    image_count: 350
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: None
    caption_extension: .txt
```

My question is how to ensure that classname is activated ? I was expecting that class_tokens was recognized by the folder name , no ? 

Thank you
